### ISSUE TITLE
Can't edit form fields when prepopulated via the values property

### ISSUE THREAD

**Issue by softelos** [theadam/react-inform#24] opened 2017-01-08 12:49 UTC
When I pass the form values from the parent component:

```
<ParentComponent>
<EditForm value={recordToEditValues} />
</ParentComponent>
```

The fields of the form appear properly populated, but I can't change their content. Typing into them has no effect (it's like their state holding their value is not changed upon the press down keys).

**Comment by theadam** [comment] 2017-01-08 15:32
If the `value` prop is set, the form will always have that value. This is similar to how react's built in controlled components work.  

More information on controlled components can be found [here](https://facebook.github.io/react/docs/forms.html).

Closing this issue as this is by design.

**Closed** 2017-01-08 15:33 UTC
